### ISSUE TITLE
request for rqt_plugin updates for Kinetic/Ubuntu 16.04

### ISSUE THREAD

**Issue by mattGT87** [KCL-Planning/ROSPlan#122]
Hello

I have been attempting to use the plugins in the "rosplan_rqt" package to understand the ROSPlan pipeline and what is going on "under the hood". The ROS service calls and subscribers in the plugin python code seem to be out of date and from an older release. This was causing them to hang indefinitely or crash on my machine. 

By replacing the service calls etc in the python code, I believe I have been able to use all of the plugins as intended except **ROSPlanDispatcher.py** to work on my machine (ROSPlanActionDispatcher.py, ROSPlanProblemViewer.py, and ROSPlanEsterelPlanViewer.py**).

For example, I have done something like change what was **rospy.wait_for_service('/kcl_rosplan/get_domain_operators')** to **rospy.wait_for_service('/rosplan_knowledge_base/domain/operators')** 
in ROSPlanActionDispatcher.py. It seems to work after these changes. 

This fix does not fully work with **ROSPlanDispatcher.py** however as this plugin seems to have been written when the parser and dispatcher handled the "CompletePlan.msg" by default instead of the "EsteralPlan.msg". Starting the parser and dispatcher node as their "simple" node counterparts does restore some of the functionality, but I cannot assemble a plan and send it via the plugin (which I'm assuming was the plugin-in's original intent and a very nice capability). 

Is there any hope for an update to these plug-ins? Specifically ROSPlanDispatcher.py and ROSPlanEsterelPlanViewer.py.

Thanks much for your time.

** I should mention there that I can currently use ROSPlanEsterelPlanViewer.py to view the plan graph with a hack I'm using(see my response in  #119 ), but I experience frequent crashes while doing so, most of the time when the graph is trying to display a mid-plan execution update.

**Comment by oscar-lima** [comment]
I believe this is solved by #112 and #149 and therefore this issue can be closed now
