### ISSUE TITLE
Bug in dispatcher

### ISSUE THREAD

**Issue by oscar-lima** [KCL-Planning/ROSPlan#169]
Does not take into account negative preconditions

**Comment by m312z** [comment]
Or numeric conditions (at least in master)! Look here:
https://github.com/KCL-Planning/ROSPlan/blob/master/rosplan_planning_system/src/PlanDispatch/PlanDispatcher.cpp
Line 128

The method only iterates through simple conditions. It should be extended to add all of the preconditions to the query.
