### ISSUE TITLE
ROS control center

### ISSUE THREAD

**Issue by nageshpindi** [KCL-Planning/ROSPlan#171]
Hi Everyone,
                  Any one has a idea about ROS-CONTROL-CENTER, i'm integrating ROSPlan with ROS-CONTROL-CENTER for user interface, It's working fine through browser but it's not working in local machine even though installed all dependencies. Can i get detailed documentation.
Thanks in advance.
NAGESH PINDI

**Comment by m312z** [comment]
> It's working fine through browser but it's not working in local machine even though installed all dependencies.

Can you be more specific? Is it ROSPlan, Control Center, or the integration that does not work? What do you mean  when you say that it works in the browser but not on the local machine? If it is a problem with control center, then you should also check the control center documentation (I am not familiar with it).

https://github.com/pantor/ros-control-center
