### ISSUE TITLE
ROSPlan on nvidia jetson tx2

### ISSUE THREAD

**Issue by Pol091994** [KCL-Planning/ROSPlan#186]
I bought a nvidia jetson tx2 and i'm trying to use ROSPlan on it. First of all there is an issue in the CmakeLists.txt file of rosplan_dependencies about the architecture of the jetson tx2, jetson tx2 require -march=armv8-a+crypto instead of -m64. 

Once i solved this problem, I following step by step both first and second rosplan tutorial, i get the following error when i try to create a plan using problem_interface and planner_interface:
![error](https://user-images.githubusercontent.com/44983923/55807951-6b8d2900-5ae3-11e9-813e-0fb2b1c3dcf9.png)

It's almost as if the popf is not performing correctly, but on another pc the same tutorials work.

**Comment by Pol091994** [comment]
Here it is
![problempddl](https://user-images.githubusercontent.com/44983923/55811089-df7e0000-5ae8-11e9-8192-80945a228c97.png)

**Comment by oscar-lima** [comment]
the plan is solvable under ubuntu based system (18.04)

command executed:
```./popf domain_turtlebot.pddl problem.pddl ```

terminal output:
```
Number of literals: 13
Constructing lookup tables: [10%] [20%] [30%] [40%] [50%] [60%] [70%] [80%] [90%] [100%] [110%] [120%] [130%] [140%]
Post filtering unreachable actions:  [10%] [20%] [30%] [40%] [50%] [60%] [70%] [80%] [90%] [100%] [110%] [120%] [130%] [140%]
No analytic limits found, not considering limit effects of goal-only operators
All the ground actions in this problem are compression-safe
Initial heuristic = 3.000
b (2.000 | 70.001)b (1.000 | 130.002);;;; Solution Found
; States evaluated: 5
; Cost: 160.003
; Time 0.00
0.000: (undock kenny wp0)  [10.000]
10.001: (localise kenny)  [60.000]
70.002: (goto_waypoint kenny wp0 wp0)  [60.000]
130.003: (dock kenny wp0)  [30.000]
```

Can you copy the attached zip files = [test.zip](https://github.com/KCL-Planning/ROSPlan/files/3059734/test.zip) under:

```/home/nvidia/catkin_ws/src/ROSPlan/rosplan_planning_system/common/bin```

and run:

```./popf domain_turtlebot.pddl problem.pddl```

**Comment by oscar-lima** [comment]
ok we found the error, popf binary is provided with ROSPlan, however this precompiled binary will work only on specific systems (tested on Ubuntu 14.04, 18.04). Your options are:

1) compile popf from source on your system ([source code here](https://github.com/LCAS/popf))
2) use another planner (e.g. sudo apt install ros-$ROS_DISTRO-ffha), 
NOTE: you will have to make your own plan output parser
3) get precompiled popf version for your system (would be hard to find...)

**Comment by moriarty** [comment]
@oscar-lima

> ok we found the error, popf binary is provided with ROSPlan, however this precompiled binary will work only on specific systems (tested on Ubuntu 16.04, 18.04).

It’s not specific Ubuntu 16.04/18.04 systems it’s that you’re only supporting the Intel/Amd 64 bit architecture. The Jetson TX1/2 also runs Ubuntu 16.04/18.04 but for arm.

If you’re precompiling a binary perhaps split out that step into another catkin package to provide the binary, because the ROS build farm can support other architectures and would be able to build the arm64 Version required for the Jetson

**Comment by oscar-lima** [comment]
Hi Alex, indeed it would be very nice to offer precompiled binaries through the ROS ecosystem. Not only for popf (which actually lives in a separate repo) but also for rosplan nodes.
