### ISSUE TITLE
Problem in changing planner

### ISSUE THREAD

**Issue by Pol091994** [KCL-Planning/ROSPlan#187]
I'm trying to change planner, from POPF to LPG, so i changed the planner interface in the file interfaced_planning_system.launch: 
![planner](https://user-images.githubusercontent.com/44983923/56890761-ad721500-6a7a-11e9-9ceb-f09a4b033e00.png)

After that i changed the argument of the interface in the planner_interface.launch in: 
![lpg](https://user-images.githubusercontent.com/44983923/56890961-35581f00-6a7b-11e9-8913-a4c375d2387b.png)

When i launch the services to produce the problem file and the plan i got this error:
![interface](https://user-images.githubusercontent.com/44983923/56891064-8700a980-6a7b-11e9-839e-02c91189dcc9.png)

But, if i try to run the same command not via rosplan, but on the linux shell i got no error and the plan is generated.

**Comment by m312z** [comment]
It looks like a problem with working directories. I'd guess that the "-out lpgplan" argument is creating the output files in a different directory from "common".

What happens when you run the same command from different directories? Are the files always created in the common folder, in bin/lpg, or in the same directory you run the command?

**Comment by Pol091994** [comment]
The files are created in the directory where i run the command

**Comment by m312z** [comment]
A quick fix would be to alter the command in the launch file to to place the output files in an absolute path. For example, "-out /home/ai/workspace/src/rosplan/rosplan_planning_system/common/lpgplan"

I can not remember the default working directory of ROS from which a command line will be run. I think it is somewhere in devel. You could find out by locating the lpgplan files.

Best regards,
Michael

**Comment by oscar-lima** [comment]
try ~/.ros

**Comment by Pol091994** [comment]
Ok perfect, now it works and the planner produce the correct file with the plan in that directory, but the topic planner_output is empty. I think the planner interface doesn't publish the plan. Is this (in planner_interface.launch) enough?
![lpg](https://user-images.githubusercontent.com/44983923/56896206-693b4080-6a8b-11e9-8476-31a64e7eec0b.png)

**Comment by m312z** [comment]
That should be enough.
@b-dorian do you know what might be happening here?

**Comment by b-dorian** [comment]
Hi, please output the plan to ../rosplan_planning_system/lpgplan.SOL. 

The interface is build to get the plan from that location. 

You can check https://github.com/KCL-Planning/ROSPlan/blob/master/rosplan_planning_system/src/PlannerInterface/LPGPlannerInterface.cpp line 67 to see what is happening behind the hood.

**Comment by Pol091994** [comment]
This is the output, the plan is correct (for what i expect). 

![lpgpiano](https://user-images.githubusercontent.com/44983923/57014520-bf85bc00-6c10-11e9-86a8-c15a3844afad.png)

**Comment by b-dorian** [comment]
I have tested everything on my end and I get the same result (nothing being published on the topic).

With the popf_planner_interface the plan is correctly published.

I have no idea at the moment why this happens, the code for the publishing is technically identical for both lpg and popf, with only the plan extraction from the text file ( the runPlanner() method) being different. 

I will have a closer look as soon as I am back at the office and get back on this.

**Comment by Pol091994** [comment]
ok, perfect. If it is possible have a feedback soon i would be grateful because i need for my degree thesis. Thank you

**Comment by b-dorian** [comment]
Refactored the code to work for the refactored version of ROSPlan and removed a bug. Pull ROSPlan from my repo (https://github.com/b-dorian/ROSPlan), or replace the LPG interface code with https://github.com/b-dorian/ROSPlan/blob/master/rosplan_planning_system/src/PlannerInterface/LPGPlannerInterface.cpp.

Also, if you pull the latest version of ROSPlan, please use as -out:  "-out $(find rosplan_planning_system)/test/lpgplan"

Let me know if you encounter any other issues.

**Comment by m312z** [comment]
Fixed in #191
