### ISSUE TITLE
TFD planner interface removes first line of a plan

### ISSUE THREAD

**Issue by varsheim** [KCL-Planning/ROSPlan#210]
Every generated plan by TFD planner gets into rostopic and further into execution without first action. The problem lays in TFDPlannerInterface.cpp

**Comment by oscar-lima** [comment]
Issue is confirmed, able to reproduce the error in my PC (Ubuntu 18.04, ROS melodic)

**Comment by oscar-lima** [comment]
#211 does indeed solve the problem, (thanks!)

**Comment by oscar-lima** [comment]
fixed by #211
