### ISSUE TITLE
TFDPlannerInterface takes least optimal plan

### ISSUE THREAD

**Issue by varsheim** [KCL-Planning/ROSPlan#217]
TFD planner's outputs often more than one file:
tfdplan.1, tfdplan.2, tfdplan.3...
where the last one contains the shortest plan.
TFDPlannerInterface takes only tfdplan.1

**Comment by varsheim** [comment]
I will probably fix this in the next few days as i use this Interface

**Comment by m312z** [comment]
Hello Varsheim, Thanks for the information!

I know it's been a while since you left the comment - but this is definitely something we should fix. Did you end up making a change? If you a can, it would be great to open a pull request for it.

Michael

**Comment by varsheim** [comment]
Hi, i actually did open a pull request some time ago, it is #218 :)
But also i saw that there were some major changes to the popf interface recently and i dont know if the way i set it up is still valid.

**Comment by oscar-lima** [comment]
solved by #218
