### ISSUE TITLE
endless loop whe instance is removed between problem generation and plan dispatch

### ISSUE THREAD

**Issue by b-dorian** [KCL-Planning/ROSPlan#224]
Esterel Plan dispatcher is stuck on an endless loop if an instance is removed from the kb before the plan is dispatched (right after generating the problem with the ProblemGenerator).

Identified the issue in lines 241-244 of EsterelPlanDispatcher.cpp

even though condition_activate_action is false, timeout_actions is also false, so replan_requested is not changed to false, hence while loop is not broken.

tried setting the timeout_actions to true in the launch file, but get an action cancelation error

![bug](https://user-images.githubusercontent.com/10816436/68812820-df8c4280-066b-11ea-8bd5-4a04106ea6b5.png)

**Comment by m312z** [comment]
> tried setting the timeout_actions to true in the launch file, but get an action cancelation error

What is the action cancellation error? If the object no longer exists, then the action's preconditions will not be achieved, and the action should time out, failing the plan.

In the case that timeout_actions is set to false, then the action will wait forever for it's preconditions to be achieved.
