### ISSUE TITLE
waypoint not found in parameter server

### ISSUE THREAD

**Issue by rakhmanu** [KCL-Planning/ROSPlan#238]
Hi,

I tried to run rosplan_turtlebot2_demo, so I can see the generated waypoints, however the robot does not move according to those waypoints( does not move at all ) And the error says waypoint not found in parameter server

Help plz

Thank you

**Comment by oscar-lima** [comment]
Issue addressed in https://github.com/KCL-Planning/rosplan_demos/issues/36 . Thanks for the report
