### ISSUE TITLE
PDDL parsing fails with ffplanner

### ISSUE THREAD

**Issue by rakhmanu** [KCL-Planning/ROSPlan#248]
Hi,

I tried to use FF planner with ffha by following this https://github.com/KCL-Planning/rosplan_demos/pull/33/files example. However, it still says that the plan was unsolvable...

The pddl domain and problem from the examples in /ROSPlan/rosplan_planning_system/test/pddl/amazon

Here is the FFplanning launch file :

<arg name="node_name"            default="rosplan_planner_interface" />
<arg name="use_problem_topic"    default="true" />
<arg name="problem_topic"        default="/rosplan_problem_interface/problem_instance" />
<arg name="planner_topic"        default="planner_output" />
<arg name="domain_path"          default="$(find ROSPlan/rosplan_planning_system/test/pddl/amazon/domain2.pddl" />
<arg name="problem_path"         default="$(find ROSPlan/rosplan_planning_system/test/pddl/amazon/problem2.pddl" />
<arg name="data_path"            default="$(find rosplan_planning_system)/test/pddl/amazonrosplan_planner_interfa/" />
<arg name="planner_command"      default="timeout 10 rosrun ffha ffha -o DOMAIN -f PROBLEM" />
<arg name="planner_interface"    default="ff_planner_interface" />
<arg name = "use_ffha"           default="true" />

<node name="$(arg node_name)" pkg="rosplan_planning_system" type="$(arg planner_interface)" respawn="false" output="screen">

	
	<param name="use_problem_topic" value="$(arg use_problem_topic)" />

	
	<param name="problem_topic" value="$(arg problem_topic)" />
	<param name="planner_topic" value="$(arg planner_topic)" />

	
	<param name="domain_path" value="$(arg domain_path)" />
	<param name="problem_path" value="$(arg problem_path)" />
	<param name="data_path" value="$(arg data_path)" />

	
	<param name="planner_command" value="$(arg planner_command)" />
	<param name="use_ffha" value="$(arg use_ffha)" />
	
</node>

And my launch file:

<include file="$(find rosplan_planning_system)/launch/includes/rosplan_planner_interfaces.launch"  >

<arg name="domain_path"	default="$(find rROSPlan/rosplan_planning_system/test/pddl/amazon/domain2.pddl" />
<arg name="problem_path" default="$(find ROSPlan/rosplan_planning_system/test/pddl/amazon/problem2.pddl" />

</include>

![fail](https://user-images.githubusercontent.com/41294651/83998510-b894b580-a99b-11ea-847f-363ff6efeb3d.png)

Thank you very much for the help

**Comment by oscar-lima** [comment]
Try using the following as planner_command:

```<arg name="planner_command"      default="timeout 10 rosrun ffha ffha -o DOMAIN -f PROBLEM" />```

and make sure that ```domain_path``` and ```problem_path``` point to the right pddl files, e.g.:

```
<arg name="domain_path"          default="$(find rosplan_planning_system)/test/pddl/amazon/domain.pddl" />
<arg name="problem_path"         default="$(find rosplan_planning_system)/test/pddl/amazon/problem.pddl" />
```

During runtime ```DOMAIN``` and ```PROBLEM``` will be replaced by the content of ```domain_path``` and ```problem_path``` (see [L65 & L67 of FFPlannerInterface](https://github.com/KCL-Planning/ROSPlan/blob/master/rosplan_planning_system/src/PlannerInterface/FFPlannerInterface.cpp#L65))

Closing issue now, feel free to reopen if needed
