### ISSUE TITLE
Questions related to ROSPlan planners  

### ISSUE THREAD

**Issue by rakhmanu** [KCL-Planning/ROSPlan#250]
Hiii,

How to use Fast Downward, TFD, LPG and SMT planners in ROSPlan framework?
I could not find  these planners in rosplan_planning_system/common/bin,  in order to write the location in planner_interface launch

Thank you very much :)
Appreciate your time

**Comment by oscar-lima** [comment]
ROSPlan providing binaries under rosplan_planning_system/common/bin is a hack that works for most users, for some planners. We are currently working on a clean solution to handle this (see https://github.com/oscar-lima/task_planners). For now, if the planner you want is not under rosplan_planning_system/common/bin , you have to manually download the planner from its original source, compile it in your machine, and write a planner interface for it. Available planner interfaces can be seen here: https://github.com/KCL-Planning/ROSPlan/tree/master/rosplan_planning_system/src/PlannerInterface (feel free to contribute with more). 

Fast Downward : http://www.fast-downward.org/
TFD : http://gki.informatik.uni-freiburg.de/tools/tfd/
LPG : https://lpg.unibs.it/lpg/
STM : https://github.com/KCL-Planning/SMTPlan

good luck !
