### ISSUE TITLE
robot does not move 

### ISSUE THREAD

**Issue by rakhmanu** [KCL-Planning/ROSPlan#252]
Hi

I am using FF planner and gave my own waypoints to the robot to follow waypoints.yaml file
I have changed the rosplan_roadmap_server.launch file to rpsimplemapServer. And the problem was generated correctly and the plan was solved. There is an error that says argument list too long, it happened after adding instances to the initial state+goals knowledge base in explore.bash file
  
I attached the output from terminal 

Thank you for you help) 

Sincerely, Ulzhalgas Rakhman

![term](https://user-images.githubusercontent.com/41294651/86002036-baa5dd80-ba4a-11ea-9977-999734432679.png)
![term2](https://user-images.githubusercontent.com/41294651/86002038-bbd70a80-ba4a-11ea-9619-c8ac23a55f3e.png)

**Comment by rakhmanu** [comment]
I solved the error shown above but robot still does not move...

**Comment by oscar-lima** [comment]
Can you please comment on how you solved this issue? (for others to know). Also the robot not moving seems like an issue that would fit better the rosplan demos repository.

**Comment by rakhmanu** [comment]
The solution was to delete the added argument attribute name in explore_common.bash

**Comment by rakhmanu** [comment]
@oscar-lima  Hi
I have got another error which says that waypoint not found in parameter server as i am using rpsimplemapserver , the data is derived from mongodb not parameter server. It means weneed to rewrite rpsimplemapserver, is that right?
Thank you
