### ISSUE TITLE
Rosplan Plan "Plan was unsolvable" error

### ISSUE THREAD

**Issue by HadeelJazzaa** [KCL-Planning/ROSPlan#263]
Both of 
![domain](https://user-images.githubusercontent.com/73404324/97092413-cb064780-163b-11eb-95dd-45c7ded619a8.JPG)
![Planning](https://user-images.githubusercontent.com/73404324/97092415-cc377480-163b-11eb-92b4-65ddc36b2535.JPG)
![PlanUnSolved](https://user-images.githubusercontent.com/73404324/97092416-ccd00b00-163b-11eb-9bd3-eb12d5253d2b.JPG)
![PopfError](https://user-images.githubusercontent.com/73404324/97092418-ccd00b00-163b-11eb-8a2c-3aa14356c383.JPG)
![problem](https://user-images.githubusercontent.com/73404324/97092419-cd68a180-163b-11eb-98f0-04e92d499181.JPG)

pddl files were validated and worked in other solvers but when It comes with the popf planner I get a segmentation fault while planning!.
 Can you help me in this Issue please?

**Comment by gerardcanal** [comment]
Hi @HadeelJazzaa,
I don't think POPF can handle this domain, as I don't believe it works with numerical comparisons as a precondition. You can use ROSPlan with many solvers (and even add your own). Check [the ROSPlan tutorials](http://kcl-planning.github.io/ROSPlan//tutorials/tutorial_02) for help in doing this, so you can use a solver that works for your domain.

I'm closing the issue as it's not directly ROSPlan-related but the domains not working with POPF (we use popf but do not maintain it, as well as the other planners).

**Comment by HadeelJazzaa** [comment]
Thanks Gerard
Yes I think  that as well.
I am not specialist in planning. So, what I am looking for is a suggestion of what planner can handle this domain?

If you recommend any!

**Comment by gerardcanal** [comment]
Hello,
I have not used those kinds of domains, so I am not 100% sure. It seems like OPTIC (which is the successor of popf) may be able to. You mentioned you used some solvers already for that domain, so if you have any that works already. I believe you need some planner that supports the `:numeric-fluents` requirement. You can check the [planning.wiki](https://planning.wiki) for more information on planners and what they support: https://planning.wiki/ref/pddl21/req#numeric-fluents. 

Hope this helps!

**Comment by HadeelJazzaa** [comment]
Ok
OPTIC sounds good.
Thank you so much Gerard for the help.

Regards.

**Comment by DerekLong101** [comment]
Actually, there is not a problem with POPF using comparison preconditions. The requirements are ill-specified here, though - you don't need disjunctive preconditions or durative actions for this domain. If you send me the domain source and problem source I'll work out why it isn't solving - it is something simple, I think.

Cheers

Derek
________________________________

**Comment by HadeelJazzaa** [comment]
Thanks a lot Derek,

I've attached the files.

Pleas have a look.

Best Regards.

Hadeel


________________________________

**Comment by DerekLong101** [comment]
Maybe mailing through github strips them off - mail me directly at derek.long@kcl.ac.uk.

Cheers

Derek
________________________________
