### ISSUE TITLE
Documentation: planning_server has wrong type

### ISSUE THREAD

**Issue by MeFisto94** [KCL-Planning/ROSPlan#265]
So, apologizes if this is just a version mismatch or something, but according to my understanding, this is just a slight fault:
https://kcl-planning.github.io/ROSPlan//documentation/interfaces/02_planner_interface.html
`planning_server` should just be an `std_srvs/Empty`, much like on the problem interface and the parameter description and the type `rosplan_dispatch_msgs/PlanningService` should only apply to `planning_server_params` service.

This also lines up with what rosservice info shows, at least in my environment

**Comment by gerardcanal** [comment]
Hi @MeFisto94,
Many thanks for spotting this! We've updated the documentation accordingly.
