### ISSUE TITLE
Multiple plans from FF planner

### ISSUE THREAD

**Issue by rakhmanu** [KCL-Planning/ROSPlan#279]
Hi,

I would like to get all possible plans from FF planner (not only optimal plan):
plan.1, plan.2, plan.3...
How i can tune the FF planner to get multiple plans?

Thank you very much,
Sincerely, Ulzhalgas Rakhman

**Comment by gerardcanal** [comment]
Dear @rakhmanu,
We are not currently involved with FF but just provide an interface to it. I don't know if FF can produce different plans (POPF does, but in that case, ROSPlan keeps the last plan, which is the best one). You can check FF documentation (https://fai.cs.uni-saarland.de/hoffmann/metric-ff.html) for more information.
