### ISSUE TITLE
Suggestion - Minor modifications to improve the system.

### ISSUE THREAD

**Issue by dgerod** [KCL-Planning/ROSPlan#28]
I have been working with ROSPlan in my research and I like it a lot. Due to my work with it I have a couple of suggestions that in my opinion improve the system and are easy to do. 

1)  The _domain.pddl_ files of the demos should not be in _rosplan_planning_system/common_ but in _rosplan_demos/common_ as they are part of the demos and not of the system.

![screenshot from 2016-06-19 11 43 40](https://cloud.githubusercontent.com/assets/1392333/16176627/46e1ae52-3613-11e6-9bfe-0b1385b76b3c.png)

2)  I suggest to create a new package inside _rosplan_ meta-package named as _rosplan_config_, to store general configuration information and tools instead being distributed inside the different components, and example of that are _MongoDB_ and _popf_ planner binary. In addition, in case that a user would like to use a different DB or planner he only need to update this package (assuming that update code is not needed).  

![screenshot from 2016-06-19 11 43 27](https://cloud.githubusercontent.com/assets/1392333/16176630/5207b90c-3613-11e6-9e08-7a05b9ae0d68.png)

I have already modified the system in my local repository as they are easy to do.

**Comment by m312z** [comment]
Hello,

Both are good ideas.

For (2) there would also need to be some update of code. I am currently writing a tutorial to do these things. However, I still think it is a good idea to separate out other libraries and tools from the ROSPlan packages.

Are you able to make a [pull request](https://help.github.com/articles/using-pull-requests/) with the changes?

Michael

**Comment by dgerod** [comment]
Yes, sure. 
Let me integrate my repository with your last updates before doing it.
