### ISSUE TITLE
Problem with simulation of action duration

### ISSUE THREAD

**Issue by erfanshojaei** [KCL-Planning/ROSPlan#298]
Hello, 
I am following the tutorial 04. 
After running the program (./tutorial.bash), I got:
***************************
[ INFO] [1627156038.393794041]: KCL: (/rosplan_plan_dispatcher) Plan received.
[ INFO] [1627156039.276491294]: KCL: (/rosplan_plan_dispatcher) Dispatching plan.
[ INFO] [1627156039.302692802]: KCL: (/rosplan_plan_dispatcher) Dispatching action [0, undock, 0.882635, 10.000000]
[ INFO] [1627156039.303001393]: KCL: (undock) action received
[ INFO] [1627156039.312532575]: KCL: (/rosplan_knowledge_base) Removing Fact (docked,0)
[ INFO] [1627156039.312793482]: KCL: (undock) Action completing with probability 1 and duration 0
[ INFO] [1627156039.312841170]: KCL: (undock) action completed successfully
[ INFO] [1627156039.322529688]: KCL: (/rosplan_knowledge_base) Adding fact (undocked kenny, 0)
[ INFO] [1627156039.376818625]: KCL: (/rosplan_plan_dispatcher) Feedback received [0, action enabled]
[ INFO] [1627156039.376860961]: KCL: (/rosplan_plan_dispatcher) Feedback received [0, action achieved]
[ INFO] [1627156039.476860613]: KCL: (/rosplan_plan_dispatcher) 0: action undock completed
[ INFO] [1627156039.502753586]: KCL: (/rosplan_plan_dispatcher) Dispatching action [1, localise, 10.883635, 60.000000]
[ INFO] [1627156039.503064413]: KCL: (localise) action received
[ INFO] [1627156039.503131880]: KCL: (localise) Action completing with probability 1 and duration 0
.............
*************************************
as you can see, duration of "undock" and "localise" actions are 10 [sec] and 60 [sec] respectively but they execute (completing) with 0 [sec] duration. 

Would you please help me to solve this problem?
Thanks in advance and regards,
Erfan

**Comment by gerardcanal** [comment]
Hi Erfan,
This is because, in tutorial 4, the simulated actions are not specifying the time, so they are instantaneous. [Tutorial 5](		https://kcl-planning.github.io/ROSPlan//tutorials/tutorial_05
) shows how to specify the duration for the simulated actions while using the Esterel plan dispatcher. I believe this should fix your issue! 

Regards,
Gerard
