### ISSUE TITLE
create a subsciber 

### ISSUE THREAD

**Issue by erfanshojaei** [KCL-Planning/ROSPlan#300]
Hello,
I am trying to create a subscriber for "/rosplan_plan_dispatcher/action_dispatch".

after I run
**rosmsg show rosplan_dispatch_msgs/ActionDispatch**, I got:

i_nt32 action_id
int32 plan_id
string name
diagnostic_msgs/KeyValue[] parameters
  string key
  string value
float32 duration
float32 dispatch_time_

for example one of my planner action is:

_action_id: 1
plan_id: 0
name: "print"
parameters: 
  - 
    key: "from"
    value: "vtx00"
  - 
    key: "to"
    value: "vtx01"
duration: 40.0
dispatch_time: 0.0010000000474974513_

I create a C++ subscriber for receiving these type of messages as:
---------------------------------------------------
#include "ros/ros.h"
#include "std_msgs/String.h"

void chatterCallback(const std_msgs::String::ConstPtr& msg)
{
 ROS_INFO("I heard: [%s]", msg->data.c_str());
}

int main(int argc, char **argv)
{
  ros::init(argc, argv, "listener");
  ros::NodeHandle n;
  ros::Subscriber sub = n.subscribe("/rosplan_plan_dispatcher/action_dispatch", 1000, chatterCallback);
  ros::spin();
  return 0;
}
---------------------------------------

but after launching the planner and the node, I received the following error:

[ERROR] [1629243694.490635676]: Client [/listener] wants topic /rosplan_plan_dispatcher/action_dispatch to have datatype/md5sum [std_msgs/String/992ce8a1687cec8c8bd883ec73ca41d1], but our version has [rosplan_dispatch_msgs/ActionDispatch/9d0c5c1ebcb48d5f31ecc568f41bc70b]. Dropping connection.

Could you please help me to solve this issue?

Thanks and regards,
Erfan

**Comment by gerardcanal** [comment]
Hi Erfan,
This is a typical ROS issue. A quick google brings to [this page](https://answers.ros.org/question/358435/md5sum-error-client-rostopic-wants-topic-move_groupdisplay_planned_path-to-have-datatypemd5sum-moveit_msgsdisplaytrajectoryc3c039-but-our-version-has/) or [this other](https://answers.ros.org/question/339058/datatypemd5sum-error/) among others. We advise trying to search for a solution before posting issues, some times they have been already solved on the internet or in another rosplan issue.

The problem sometimes is that there are compilation issues and two nodes use different versions of the message. in your case it is something different, es explained in [the second answer I linked](https://answers.ros.org/question/339058/datatypemd5sum-error/):

The action_dispatch topic has type `rosplan_dispatch_msgs/ActionDispatch` as you can see running:
```
$ rostopic type /rosplan_plan_dispatcher/action_dispatch 
rosplan_dispatch_msgs/ActionDispatch
```

However, you are subscribing to `std_msgs/String` in your chatterCallback. Thus, your node is trying to receive a String while it's being sent an ActionDispatch message. Please include and use the message that the topic is using.

Example:
```
#include "rosplan_dispatch_msgs/ActionDispatch.h"

void chatterCallback(const rosplan_dispatch_msgs::ActionDispatch::ConstPtr& msg)
```
