### ISSUE TITLE
The steps to interface other planners to ROSPlan

### ISSUE THREAD

**Issue by bhomaidan1990** [KCL-Planning/ROSPlan#314]
Hi, 
Can you please tell me **the steps to interface other planners to ROSPlan** such as [Lilotane](https://github.com/domschrei/lilotane)? 

Is it only about writing a [planner interface](https://github.com/KCL-Planning/ROSPlan/tree/master/rosplan_planning_system/include/rosplan_planning_system/PlannerInterface)? or should I do more steps?

Because I didn't find this point in the [tutorial](https://kcl-planning.github.io/ROSPlan//documentation/interfaces/02_planner_interface.html), thanks in advance.

**Comment by gerardcanal** [comment]
Hi @bhomaidan1990,
In theory, it should be enough with writing a planner interface (at least for PDDL planners). I have not worked with HDDL in ROSPlan, but there's an extension with the CHIMP planner, so I would start by checking how was that interface done and do something similar for Lilotane (as long as you output the same I believe it should work).
