### ISSUE TITLE
Run the demo with ROS Noetic 

### ISSUE THREAD

**Issue by memento197** [KCL-Planning/ROSPlan#326]
Hello everyone, I was wondering whether the Turtlebot demos would also work on ROS Noetic (Ubuntu 20.04)

**Comment by KaushalkumarPatel** [comment]
Hello @memento197 Did you run the demos no ROS Noetic successfully ? Please confirm

**Comment by memento197** [comment]
Hello @KaushalkumarPatel, unfortunately not. I closed the issue because I had already reached the submission deadline in my project.
