### ISSUE TITLE
ResourceNotFound: rosplan_config

### ISSUE THREAD

**Issue by HelenHarman** [KCL-Planning/ROSPlan#40]
When trying to launch the demo I receive an error message saying:
> ResourceNotFound: rosplan_config

I see that the files that were in rosplan_config have been moved to other packages, however rosplan_config is still used within several launch files (interfaced_planning_system.launch and rosplan_roadmap_server.launch).

**Comment by m312z** [comment]
Thanks for the info!
I've fixed the two files you mentioned. I'll do another pass to find others.

Michael
