### ISSUE TITLE
Another error with Turtlebot Demo

### ISSUE THREAD

**Issue by EsdrasChaves** [KCL-Planning/ROSPlan#43]
Hi there,

I had to format my computer and trying to run the turtlebot demo again, I got two errors that didn't appear before.

I got this error message

` ERROR: Service [/kcl_rosplan/roadmap_server/create_prm] is not available.`

while running:

` sh src/rosplan/rosplan_demos/scripts/turtlebot_explore.bash`

and

` ERROR: cannot launch node of type [rosplan_interface_mapping/rproadmapServer]: can't locate node [rproadmapServer] in package [rosplan_interface_mapping]
ERROR: cannot launch node of type [rosplan_interface_movebase/rpmovebase]: can't locate node [rpmovebase] in package [rosplan_interface_movebase] `

while running:

` roslaunch rosplan_demos turtlebot.launch `

Cheers,
Esdras Chaves

**Comment by m312z** [comment]
It seems that the map and movebase interface nodes are not starting.

You can also try running them in isolation. After sourcing and starting the master:
rosrun rosplan_interface_movebase rpmovebase
and
rosrun rosplan_interface_mapping rproadmapServer

These should work. If not can you check to be sure they are compiled?
