### ISSUE TITLE
Some services in rosplan_knowledge_msgs that are not part of ROSPlan

### ISSUE THREAD

**Issue by dgerod** [KCL-Planning/ROSPlan#45]
The following services should not be part of _rosplan_knowledge_msgs_:

- RemoveWaypoint.srv
- AddWaypoint.srv
- CreatePRM.srv

as they are are specific of _rosplan_interface_mapping_ package.

In addition, I think that _rosplan_interface_movebase_ and _rosplan_interface_mapping_ should not be part of the ROSPlan repository. They should be stored in a different repository, maybe named as _rosplan_interface_robot_,  in which generic robot interfaces as these two would be stored.

**Comment by m312z** [comment]
This comes from the time in which waypoints were an integral part of the Knowledge Base. Now there should be a new package, i.e. "rosplan_interface_mapping_msgs"

> In addition...
I tend to agree. (Similar to the existing rosplan_interface_turtlebot2 and rosplan_interface_COLA2). The trick will be to do this in a way that does not break the demos people are already using.
