### ISSUE TITLE
cannot launch node of type [rosplan_knowledge_base/knowledgeBase] ...

### ISSUE THREAD

**Issue by mokhtarivahid** [KCL-Planning/ROSPlan#48]
Hello,

I am getting the following errors (errors are in bold):

`vahid@vahid-ThinkPad-W520:~$ roslaunch rosplan_demos turtlebot.launch 
... logging to /home/vahid/.ros/log/1f412ed4-2f39-11e7-9670-0024d7ce5a44/roslaunch-vahid-ThinkPad-W520-15251.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://vahid-ThinkPad-W520:43553/

SUMMARY
========

PARAMETERS
 * /amcl/base_frame_id
 * /amcl/gui_publish_rate
 * /amcl/initial_pose_a
 * /amcl/initial_pose_x
 * /amcl/initial_pose_y
 * /amcl/kld_err
 * /amcl/kld_z
 * /amcl/laser_lambda_short
 * /amcl/laser_likelihood_max_dist
 * /amcl/laser_max_beams
 * /amcl/laser_max_range
 * /amcl/laser_model_type
 * /amcl/laser_sigma_hit
 * /amcl/laser_z_hit
 * /amcl/laser_z_max
 * /amcl/laser_z_rand
 * /amcl/laser_z_short
 * /amcl/max_particles
 * /amcl/min_particles
 * /amcl/odom_alpha1
 * /amcl/odom_alpha2
 * /amcl/odom_alpha3
 * /amcl/odom_alpha4
 * /amcl/odom_alpha5
 * /amcl/odom_frame_id
 * /amcl/odom_model_type
 * /amcl/recovery_alpha_fast
 * /amcl/recovery_alpha_slow
 * /amcl/resample_interval
 * /amcl/transform_tolerance
 * /amcl/update_min_a
 * /amcl/update_min_d
 * /amcl/use_map_topic
 * /bumper2pointcloud/pointcloud_radius
 * /cmd_vel_mux/yaml_cfg_file
 * /depthimage_to_laserscan/output_frame_id
 * /depthimage_to_laserscan/range_min
 * /depthimage_to_laserscan/scan_height
 * /move_base/TrajectoryPlannerROS/acc_lim_theta
 * /move_base/TrajectoryPlannerROS/acc_lim_x
 * /move_base/TrajectoryPlannerROS/acc_lim_y
 * /move_base/TrajectoryPlannerROS/dwa
 * /move_base/TrajectoryPlannerROS/gdist_scale
 * /move_base/TrajectoryPlannerROS/heading_lookahead
 * /move_base/TrajectoryPlannerROS/holonomic_robot
 * /move_base/TrajectoryPlannerROS/max_vel_theta
 * /move_base/TrajectoryPlannerROS/max_vel_x
 * /move_base/TrajectoryPlannerROS/max_vel_y
 * /move_base/TrajectoryPlannerROS/meter_scoring
 * /move_base/TrajectoryPlannerROS/min_in_place_vel_theta
 * /move_base/TrajectoryPlannerROS/min_vel_theta
 * /move_base/TrajectoryPlannerROS/min_vel_x
 * /move_base/TrajectoryPlannerROS/min_vel_y
 * /move_base/TrajectoryPlannerROS/occdist_scale
 * /move_base/TrajectoryPlannerROS/oscillation_reset_dist
 * /move_base/TrajectoryPlannerROS/pdist_scale
 * /move_base/TrajectoryPlannerROS/sim_time
 * /move_base/TrajectoryPlannerROS/vtheta_samples
 * /move_base/TrajectoryPlannerROS/vx_samples
 * /move_base/TrajectoryPlannerROS/vy_samples
 * /move_base/TrajectoryPlannerROS/xy_goal_tolerance
 * /move_base/TrajectoryPlannerROS/yaw_goal_tolerance
 * /move_base/controller_frequency
 * /move_base/controller_patience
 * /move_base/global_costmap/bump/clearing
 * /move_base/global_costmap/bump/data_type
 * /move_base/global_costmap/bump/marking
 * /move_base/global_costmap/bump/max_obstacle_height
 * /move_base/global_costmap/bump/min_obstacle_height
 * /move_base/global_costmap/bump/topic
 * /move_base/global_costmap/global_frame
 * /move_base/global_costmap/inflation_radius
 * /move_base/global_costmap/map_type
 * /move_base/global_costmap/max_obstacle_height
 * /move_base/global_costmap/observation_sources
 * /move_base/global_costmap/obstacle_range
 * /move_base/global_costmap/origin_z
 * /move_base/global_costmap/publish_frequency
 * /move_base/global_costmap/publish_voxel_map
 * /move_base/global_costmap/raytrace_range
 * /move_base/global_costmap/robot_base_frame
 * /move_base/global_costmap/robot_radius
 * /move_base/global_costmap/scan/clearing
 * /move_base/global_costmap/scan/data_type
 * /move_base/global_costmap/scan/marking
 * /move_base/global_costmap/scan/max_obstacle_height
 * /move_base/global_costmap/scan/min_obstacle_height
 * /move_base/global_costmap/scan/topic
 * /move_base/global_costmap/static_map
 * /move_base/global_costmap/transform_tolerance
 * /move_base/global_costmap/update_frequency
 * /move_base/global_costmap/z_resolution
 * /move_base/global_costmap/z_voxels
 * /move_base/local_costmap/bump/clearing
 * /move_base/local_costmap/bump/data_type
 * /move_base/local_costmap/bump/marking
 * /move_base/local_costmap/bump/max_obstacle_height
 * /move_base/local_costmap/bump/min_obstacle_height
 * /move_base/local_costmap/bump/topic
 * /move_base/local_costmap/global_frame
 * /move_base/local_costmap/height
 * /move_base/local_costmap/inflation_radius
 * /move_base/local_costmap/map_type
 * /move_base/local_costmap/max_obstacle_height
 * /move_base/local_costmap/observation_sources
 * /move_base/local_costmap/obstacle_range
 * /move_base/local_costmap/origin_z
 * /move_base/local_costmap/publish_frequency
 * /move_base/local_costmap/publish_voxel_map
 * /move_base/local_costmap/raytrace_range
 * /move_base/local_costmap/resolution
 * /move_base/local_costmap/robot_base_frame
 * /move_base/local_costmap/robot_radius
 * /move_base/local_costmap/rolling_window
 * /move_base/local_costmap/scan/clearing
 * /move_base/local_costmap/scan/data_type
 * /move_base/local_costmap/scan/marking
 * /move_base/local_costmap/scan/max_obstacle_height
 * /move_base/local_costmap/scan/min_obstacle_height
 * /move_base/local_costmap/scan/topic
 * /move_base/local_costmap/static_map
 * /move_base/local_costmap/transform_tolerance
 * /move_base/local_costmap/update_frequency
 * /move_base/local_costmap/width
 * /move_base/local_costmap/z_resolution
 * /move_base/local_costmap/z_voxels
 * /move_base/oscillation_distance
 * /move_base/oscillation_timeout
 * /move_base/planner_frequency
 * /move_base/planner_patience
 * /move_base/shutdown_costmaps
 * /navigation_velocity_smoother/accel_lim_v
 * /navigation_velocity_smoother/accel_lim_w
 * /navigation_velocity_smoother/decel_factor
 * /navigation_velocity_smoother/frequency
 * /navigation_velocity_smoother/robot_feedback
 * /navigation_velocity_smoother/speed_lim_v
 * /navigation_velocity_smoother/speed_lim_w
 * /robot_description
 * /robot_state_publisher/publish_frequency
 * /rosdistro
 * /rosplan/data_path
 * /rosplan/domain_path
 * /rosplan/planner_path
 * /rosplan_interface_movebase/action_server
 * /rosplan_interface_movebase/pddl_action_name
 * /rosplan_knowledge_base/database_path
 * /rosplan_knowledge_base/use_unknowns
 * /rosplan_planning_system/data_path
 * /rosplan_planning_system/generate_default_problem
 * /rosplan_planning_system/max_dispatch_attempts
 * /rosplan_planning_system/planner_command
 * /rosplan_planning_system/problem_path
 * /rosplan_planning_system/strl_file_path
 * /rosplan_roadmap_server/cost_map_topic
 * /rosplan_roadmap_server/odom_topic
 * /rosplan_roadmap_server/rosplan/data_path
 * /rosplan_roadmap_server/static_map_service
 * /rosplan_roadmap_server/use_static_map
 * /rosplan_scene_database/database_path
 * /rosversion
 * /use_sim_time

NODES
  /
    amcl (amcl/amcl)
    bumper2pointcloud (nodelet/nodelet)
    cmd_vel_mux (nodelet/nodelet)
    depthimage_to_laserscan (nodelet/nodelet)
    gazebo (gazebo_ros/gzserver)
    gazebo_gui (gazebo_ros/gzclient)
    kobuki_safety_controller (nodelet/nodelet)
    laserscan_nodelet_manager (nodelet/nodelet)
    map_server (map_server/map_server)
    mobile_base_nodelet_manager (nodelet/nodelet)
    move_base (move_base/move_base)
    navigation_velocity_smoother (nodelet/nodelet)
    robot_state_publisher (robot_state_publisher/robot_state_publisher)
    rosplan_interface_movebase (rosplan_interface_movebase/rpmovebase)
    rosplan_knowledge_base (rosplan_knowledge_base/knowledgeBase)
    rosplan_planning_system (rosplan_planning_system/planner)
    rosplan_roadmap_server (rosplan_interface_mapping/rproadmapServer)
    rosplan_scene_database (mongodb_store/mongodb_server.py)
    rosplan_scene_message_store (mongodb_store/message_store_node.py)
    rviz (rviz/rviz)
    spawn_turtlebot_model (gazebo_ros/spawn_model)

auto-starting new master
process[master]: started with pid [15268]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to 1f412ed4-2f39-11e7-9670-0024d7ce5a44
process[rosout-1]: started with pid [15281]
started core service [/rosout]
process[gazebo-2]: started with pid [15295]
process[gazebo_gui-3]: started with pid [15301]
Gazebo multi-robot simulator, version 1.9.6
Copyright (C) 2014 Open Source Robotics Foundation.
Released under the Apache 2 License.
http://gazebosim.org

process[spawn_turtlebot_model-4]: started with pid [15310]
Gazebo multi-robot simulator, version 1.9.6
Copyright (C) 2014 Open Source Robotics Foundation.
Released under the Apache 2 License.
http://gazebosim.org

process[mobile_base_nodelet_manager-5]: started with pid [15312]
Msg Waiting for master.process[cmd_vel_mux-6]: started with pid [15340]
process[bumper2pointcloud-7]: started with pid [15371]
[ INFO] [1493730805.508278681]: Finished loading Gazebo ROS API Plugin.
Msg Waiting for master[ INFO] [1493730805.509206305]: waitForService: Service [/gazebo/set_physics_properties] has not been advertised, waiting...

Msg Connected to gazebo master @ http://127.0.0.1:11345
Msg Publicized address: 192.168.26.135
process[robot_state_publisher-8]: started with pid [15417]
process[laserscan_nodelet_manager-9]: started with pid [15447]
process[depthimage_to_laserscan-10]: started with pid [15476]
process[map_server-11]: started with pid [15494]
process[amcl-12]: started with pid [15510]
process[navigation_velocity_smoother-13]: started with pid [15593]
process[kobuki_safety_controller-14]: started with pid [15682]
process[move_base-15]: started with pid [15777]
process[rviz-16]: started with pid [15837]
**ERROR: cannot launch node of type [rosplan_knowledge_base/knowledgeBase]: can't locate node [knowledgeBase] in package [rosplan_knowledge_base]**
process[rosplan_scene_database-18]: started with pid [15913]
process[rosplan_scene_message_store-19]: started with pid [15936]
**ERROR: cannot launch node of type [rosplan_planning_system/planner]: can't locate node [planner] in package [rosplan_planning_system]**
**ERROR: cannot launch node of type [rosplan_interface_mapping/rproadmapServer]: can't locate node [rproadmapServer] in package [rosplan_interface_mapping]**
**ERROR: cannot launch node of type [rosplan_interface_movebase/rpmovebase]: can't locate node [rpmovebase] in package [rosplan_interface_movebase]**

Msg Connected to gazebo master @ http://127.0.0.1:11345
Msg Publicized address: 192.168.26.135
Warning [ModelDatabase.cc:335] Getting models from[http://gazebosim.org/models/]. This may take a few seconds.
**Error [ModelDatabase.cc:408] Unable to download model[model://dumpster/meshes/dumpster.dae]**
**Error [SystemPaths.cc:371] File or path does not exist[""]**
**Error [MeshShape.cc:64] No mesh specified**
**Error [ModelDatabase.cc:408] Unable to download model[model://cube_20k/meshes/cube_20k.stl]**
**Error [SystemPaths.cc:371] File or path does not exist[""]**
**Error [MeshShape.cc:64] No mesh specified**
Msg Waiting for model database update to complete...
[ INFO] [1493730875.604686684, 0.010000000]: Camera Plugin (robotNamespace = /), Info: Using the 'robotNamespace' param: '/'
[ INFO] [1493730875.672449451, 0.010000000]: Camera Plugin (ns = /)  <tf_prefix_>, set to ""
Dbg Plugin model name: mobile_base
[ INFO] [1493730875.729310046, 0.010000000]: Will publish tf. [mobile_base]
[ INFO] [1493730875.738222293, 0.010000000]: GazeboRosKobuki plugin ready to go! [mobile_base]
Warning [RaySensor.cc:283] ranges not constructed yet (zero sized)
Warning [RaySensor.cc:283] ranges not constructed yet (zero sized)
Warning [RaySensor.cc:283] ranges not constructed yet (zero sized)
Warning [RaySensor.cc:283] ranges not constructed yet (zero sized)
Warning [RaySensor.cc:283] ranges not constructed yet (zero sized)
Warning [RaySensor.cc:283] ranges not constructed yet (zero sized)
[ INFO] [1493730875.750038303, 0.030000000]: waitForService: Service [/gazebo/set_physics_properties] is now available.
[ INFO] [1493730875.795279728, 0.070000000]: Physics dynamic reconfigure ready.
[spawn_turtlebot_model-4] process has finished cleanly
log file: /home/vahid/.ros/log/1f412ed4-2f39-11e7-9670-0024d7ce5a44/spawn_turtlebot_model-4*.log
**Error [ModelDatabase.cc:408] Unable to download model[model://dumpster/meshes/dumpster.dae]
Error [SystemPaths.cc:371] File or path does not exist[""]
Error [Visual.cc:2072] No mesh specified
Error [ModelDatabase.cc:408] Unable to download model[model://dumpster/materials/scripts]
Error [SystemPaths.cc:371] File or path does not exist[""]
Error [RenderEngine.cc:409] URI doesn't exist[model://dumpster/materials/scripts]
Error [ModelDatabase.cc:408] Unable to download model[model://dumpster/materials/textures]
Error [SystemPaths.cc:371] File or path does not exist[""]
Error [RenderEngine.cc:409] URI doesn't exist[model://dumpster/materials/textures]**
Warning [Visual.cc:774] Unable to get Material[Dumpster/Diffuse] for Geometry[Dumpster::link::visual. Object will appear white
**Error [ModelDatabase.cc:408] Unable to download model[model://dumpster/materials/scripts]
Error [SystemPaths.cc:371] File or path does not exist[""]
Error [RenderEngine.cc:409] URI doesn't exist[model://dumpster/materials/scripts]
Error [ModelDatabase.cc:408] Unable to download model[model://dumpster/materials/textures]
Error [SystemPaths.cc:371] File or path does not exist[""]
Error [RenderEngine.cc:409] URI doesn't exist[model://dumpster/materials/textures]
Error [ModelDatabase.cc:408] Unable to download model[model://dumpster/materials/scripts]
Error [SystemPaths.cc:371] File or path does not exist[""]
Error [RenderEngine.cc:409] URI doesn't exist[model://dumpster/materials/scripts]
Error [ModelDatabase.cc:408] Unable to download model[model://dumpster/materials/textures]
Error [SystemPaths.cc:371] File or path does not exist[""]
Error [RenderEngine.cc:409] URI doesn't exist[model://dumpster/materials/textures]
Error [ModelDatabase.cc:408] Unable to download model[model://cube_20k/meshes/cube_20k.stl]
Error [SystemPaths.cc:371] File or path does not exist[""]
Error [Visual.cc:2072] No mesh specified
Error [ModelDatabase.cc:408] Unable to download model[model://dumpster/meshes/dumpster.dae]
Error [SystemPaths.cc:371] File or path does not exist[""]
Error [Visual.cc:2072] No mesh specified
Error [ModelDatabase.cc:408] Unable to download model[model://dumpster/materials/scripts]
Error [SystemPaths.cc:371] File or path does not exist[""]
Error [RenderEngine.cc:409] URI doesn't exist[model://dumpster/materials/scripts]
Error [ModelDatabase.cc:408] Unable to download model[model://dumpster/materials/textures]
Error [SystemPaths.cc:371] File or path does not exist[""]
Error [RenderEngine.cc:409] URI doesn't exist[model://dumpster/materials/textures]**
Warning [Visual.cc:774] Unable to get Material[Dumpster/Diffuse] for Geometry[Dumpster::link::visual. Object will appear white
**Error [ModelDatabase.cc:408] Unable to download model[model://dumpster/materials/scripts]
Error [SystemPaths.cc:371] File or path does not exist[""]
Error [RenderEngine.cc:409] URI doesn't exist[model://dumpster/materials/scripts]
Error [ModelDatabase.cc:408] Unable to download model[model://dumpster/materials/textures]
Error [SystemPaths.cc:371] File or path does not exist[""]
Error [RenderEngine.cc:409] URI doesn't exist[model://dumpster/materials/textures]
Error [ModelDatabase.cc:408] Unable to download model[model://dumpster/materials/scripts]
Error [SystemPaths.cc:371] File or path does not exist[""]
Error [RenderEngine.cc:409] URI doesn't exist[model://dumpster/materials/scripts]
Error [ModelDatabase.cc:408] Unable to download model[model://dumpster/materials/textures]
Error [SystemPaths.cc:371] File or path does not exist[""]
Error [RenderEngine.cc:409] URI doesn't exist[model://dumpster/materials/textures]
Error [ModelDatabase.cc:408] Unable to download model[model://cube_20k/meshes/cube_20k.stl]
Error [SystemPaths.cc:371] File or path does not exist[""]
Error [Visual.cc:2072] No mesh specified
Error [ModelDatabase.cc:408] Unable to download model[model://jersey_barrier/meshes/jersey_barrier.dae]
Error [SystemPaths.cc:371] File or path does not exist[""]
Error [Visual.cc:2072] No mesh specified
Error [ModelDatabase.cc:408] Unable to download model[model://dumpster/meshes/dumpster.dae]
Error [SystemPaths.cc:371] File or path does not exist[""]
Error [Visual.cc:2072] No mesh specified
Error [ModelDatabase.cc:408] Unable to download model[model://cube_20k/meshes/cube_20k.stl]
Error [SystemPaths.cc:371] File or path does not exist[""]
Error [Visual.cc:2072] No mesh specified
Error [ModelDatabase.cc:408] Unable to download model[model://jersey_barrier/meshes/jersey_barrier.dae]
Error [SystemPaths.cc:371] File or path does not exist[""]
Error [Visual.cc:2072] No mesh specified
Error [ModelDatabase.cc:408] Unable to download model[model://dumpster/meshes/dumpster.dae]
Error [SystemPaths.cc:371] File or path does not exist[""]
Error [Visual.cc:2072] No mesh specified
Error [ModelDatabase.cc:408] Unable to download model[model://cube_20k/meshes/cube_20k.stl]
Error [SystemPaths.cc:371] File or path does not exist[""]
Error [Visual.cc:2072] No mesh specified**
[ INFO] [1493730877.318801892, 1.590000000]: Loading from pre-hydro parameter style
[ INFO] [1493730877.360633013, 1.630000000]: Using plugin "static_layer"
[ INFO] [1493730877.428544205, 1.700000000]: Requesting the map...
[ INFO] [1493730877.626382263, 1.900000000]: Resizing costmap to 231 X 194 at 0.050000 m/pix
[ INFO] [1493730877.725980765, 2.000000000]: Received a 231 X 194 map at 0.050000 m/pix
[ INFO] [1493730877.730298825, 2.000000000]: Using plugin "obstacle_layer"
[ INFO] [1493730877.732612955, 2.000000000]:     Subscribed to Topics: scan bump
[ INFO] [1493730877.800121512, 2.070000000]: Using plugin "inflation_layer"
[ INFO] [1493730877.954134676, 2.220000000]: Loading from pre-hydro parameter style
[ INFO] [1493730877.997926242, 2.270000000]: Using plugin "obstacle_layer"
[ INFO] [1493730878.060802801, 2.330000000]:     Subscribed to Topics: scan bump
[ INFO] [1493730878.121963235, 2.390000000]: Using plugin "inflation_layer"
[ INFO] [1493730878.237420707, 2.500000000]: Created local_planner base_local_planner/TrajectoryPlannerROS
[ INFO] [1493730878.260525950, 2.530000000]: Sim period is set to 0.20
[ INFO] [1493730879.034581690, 3.300000000]: Recovery behavior will clear layer obstacles
[ INFO] [1493730879.103149710, 3.370000000]: Recovery behavior will clear layer obstacles
[ INFO] [1493730879.145982205, 3.410000000]: odom received!
`

Thank you for your help.
Best

**Comment by m312z** [comment]
The errors of type:
> ERROR: cannot launch node of type [rosplan_knowledge_base/knowledgeBase]: can't locate node [knowledgeBase] in package [rosplan_knowledge_base]
will be fixed by sourcing the workspace before launching. If not, make sure that the packages are properly compiled (look for them in the devel folder) and try to find them using roscd.

The other errors are from Gazebo, which might be having problems downloading models. You can download them manually and put them in the right directory. I found the same issue here:
http://answers.gazebosim.org/question/4399/turtlebot_gazebo-world-not-loading-models/

Hope this helps,
Michael

**Comment by mokhtarivahid** [comment]
Hi Michael,
It was resolved by sourcing the workspace.
I also downloaded the models and added to gazebo, and now, seems it works well.

I am facing a new error in running "rqt --standalone rosplan_rqt.dispatcher.ROSPlanDispatcher" as follow:

`vahid@vahid-ThinkPad-W520:~$ rqt --standalone rosplan_rqt.dispatcher.ROSPlanDispatcher
RosPluginProvider.load(rosplan_rqt/ROSPlanDispatcher) exception raised in __builtin__.__import__(rosplan_rqt.dispatcher, [ROSPlanDispatcher]):
Traceback (most recent call last):
  File "/opt/ros/hydro/lib/python2.7/dist-packages/rqt_gui/ros_plugin_provider.py", line 77, in load
    module = __builtin__.__import__(attributes['module_name'], fromlist=[attributes['class_from_class_type']], level=0)
  File "/home/vahid/ROSPlan/src/rosplan/rosplan_rqt/src/rosplan_rqt/dispatcher.py", line 3, in <module>
    from .ROSPlanDispatcher import PlanViewWidget
  File "/home/vahid/ROSPlan/src/rosplan/rosplan_rqt/src/rosplan_rqt/ROSPlanDispatcher.py", line 13, in <module>
    from rosplan_dispatch_msgs.msg import *
ImportError: No module named rosplan_dispatch_msgs.msg

PluginManager._load_plugin() could not load plugin "rosplan_rqt/ROSPlanDispatcher":
Traceback (most recent call last):
  File "/opt/ros/hydro/lib/python2.7/dist-packages/qt_gui/plugin_handler.py", line 98, in load
    self._load()
  File "/opt/ros/hydro/lib/python2.7/dist-packages/qt_gui/plugin_handler_direct.py", line 54, in _load
    self._plugin = self._plugin_provider.load(self._instance_id.plugin_id, self._context)
  File "/opt/ros/hydro/lib/python2.7/dist-packages/qt_gui/composite_plugin_provider.py", line 71, in load
    instance = plugin_provider.load(plugin_id, plugin_context)
  File "/opt/ros/hydro/lib/python2.7/dist-packages/qt_gui/composite_plugin_provider.py", line 71, in load
    instance = plugin_provider.load(plugin_id, plugin_context)
  File "/opt/ros/hydro/lib/python2.7/dist-packages/rqt_gui_py/ros_py_plugin_provider.py", line 60, in load
    return super(RosPyPluginProvider, self).load(plugin_id, plugin_context)
  File "/opt/ros/hydro/lib/python2.7/dist-packages/qt_gui/composite_plugin_provider.py", line 71, in load
    instance = plugin_provider.load(plugin_id, plugin_context)
  File "/opt/ros/hydro/lib/python2.7/dist-packages/rqt_gui/ros_plugin_provider.py", line 83, in load
    raise e
ImportError: No module named rosplan_dispatch_msgs.msg
`

Do you have any idea?
Thank you.
Vahid

**Comment by mokhtarivahid** [comment]
I forgot to source it again.
It is Ok now.
Thank you.

**Comment by dgerod** [comment]
It means to use "source" in your local workspace instead to the ROS distribution one. So, calling "source devel/setup.bash" instead "source /opt/ros/DISTRIBUTION/setup.bash"

This command add all your local package to the ROS path so ROS tools is able to find them. To check if your local packages are correctly added you could use "roscd NAME_OF_YOUR_PACKAGE" or "rospack list | grep NAME_OF_YOUR_PACKAGE."

**Comment by tomitrescak** [comment]
Thank you!
