### ISSUE TITLE
Problem Compilation ROSPlan (Invoking "make -j8 -l8" failed)

### ISSUE THREAD

**Issue by ismaisma** [KCL-Planning/ROSPlan#52]
Hi, 
I tried to re-install ROSPLAN but I have problem with catkin_make, I have the following message: 

`Base path: /home/srp/ROSPlan
Source space: /home/srp/ROSPlan/src
Build space: /home/srp/ROSPlan/build
Devel space: /home/srp/ROSPlan/devel
Install space: /home/srp/ROSPlan/install
####
####
####
####
[  0%] [  0%] Built target diagnostic_msgs_generate_messages_py
Built target actionlib_msgs_generate_messages_py
[  0%] Built target std_msgs_generate_messages_py
[  0%] Built target _rosplan_dispatch_msgs_generate_messages_check_deps_PlanGoal
[  0%] [  0%] [  0%] Built target _rosplan_dispatch_msgs_generate_messages_check_deps_CompletePlan
Built target _rosplan_dispatch_msgs_generate_messages_check_deps_PlanActionFeedback
Built target _rosplan_dispatch_msgs_generate_messages_check_deps_PlanActionResult
[  0%] Built target _rosplan_dispatch_msgs_generate_messages_check_deps_PlanFeedback
[  0%] [  0%] Built target _rosplan_dispatch_msgs_generate_messages_check_deps_ActionFeedback
Built target actionlib_msgs_generate_messages_cpp
[  0%] [  0%] Built target _rosplan_dispatch_msgs_generate_messages_check_deps_PlanResult
Built target diagnostic_msgs_generate_messages_cpp
[  0%] Built target _rosplan_dispatch_msgs_generate_messages_check_deps_PlanningService
[  0%] [  0%] [  0%] Built target std_msgs_generate_messages_cpp
Built target diagnostic_msgs_generate_messages_lisp
Built target actionlib_msgs_generate_messages_lisp
[  0%] Built target std_msgs_generate_messages_lisp
[  0%] Built target _rosplan_dispatch_msgs_generate_messages_check_deps_PlanActionGoal
[  0%] [  0%] Built target _rosplan_dispatch_msgs_generate_messages_check_deps_ActionDispatch
Built target _rosplan_dispatch_msgs_generate_messages_check_deps_PlanAction
[  0%] Built target _rosplan_knowledge_msgs_generate_messages_check_deps_GetDomainOperatorService
[  0%] [  0%] Built target _rosplan_knowledge_msgs_generate_messages_check_deps_RemoveWaypoint
Built target _rosplan_knowledge_msgs_generate_messages_check_deps_KnowledgeItem
[  0%] Built target _rosplan_knowledge_msgs_generate_messages_check_deps_Filter
[  0%] Built target _rosplan_knowledge_msgs_generate_messages_check_deps_KnowledgeUpdateServiceArray
[  0%] [  0%] Built target _rosplan_knowledge_msgs_generate_messages_check_deps_AddWaypoint
[  0%] Built target _rosplan_knowledge_msgs_generate_messages_check_deps_GenerateProblemService
Built target geometry_msgs_generate_messages_py
[  0%] Built target _rosplan_knowledge_msgs_generate_messages_check_deps_GetAttributeService
[  0%] Built target _rosplan_knowledge_msgs_generate_messages_check_deps_KnowledgeUpdateService
[  0%] Built target _rosplan_knowledge_msgs_generate_messages_check_deps_DomainFormula
[  0%] Built target _rosplan_knowledge_msgs_generate_messages_check_deps_GetDomainTypeService
[  0%] Built target _rosplan_knowledge_msgs_generate_messages_check_deps_Notification
[  0%] [  0%] Built target _rosplan_knowledge_msgs_generate_messages_check_deps_GetDomainAttributeService
Built target _rosplan_knowledge_msgs_generate_messages_check_deps_GetInstanceService
[  0%] Built target _rosplan_knowledge_msgs_generate_messages_check_deps_DomainOperator
[  0%] Built target geometry_msgs_generate_messages_cpp
[  0%] [  0%] Built target geometry_msgs_generate_messages_lisp
Built target actionlib_generate_messages_lisp
[  0%] Built target _rosplan_knowledge_msgs_generate_messages_check_deps_KnowledgeQueryService
[  0%] Built target roscpp_generate_messages_cpp
[  0%] Built target rosgraph_msgs_generate_messages_lisp
[  0%] Built target rosgraph_msgs_generate_messages_py
[  0%] [  0%] Built target roscpp_generate_messages_py
Built target roscpp_generate_messages_lisp
[  0%] [  0%] Built target rosgraph_msgs_generate_messages_cpp
[  0%] Built target _rosplan_knowledge_msgs_generate_messages_check_deps_CreatePRM
Built target actionlib_generate_messages_py
[  0%] Built target _rosplan_knowledge_msgs_generate_messages_check_deps_GetDomainPredicateDetailsService
[  0%] [  0%] [  0%] [  0%] Built target actionlib_generate_messages_cpp
Built target std_srvs_generate_messages_cpp
Built target std_srvs_generate_messages_py
Built target _rosplan_knowledge_msgs_generate_messages_check_deps_GetDomainOperatorDetailsService
[  0%] [  0%] Built target std_srvs_generate_messages_lisp
Built target mongodb_store_generate_messages_lisp
[  0%] Built target move_base_msgs_generate_messages_py
[  0%] [  0%] [  0%] [  0%] [  0%] Built target mongodb_store_generate_messages_cpp
Built target mongodb_store_msgs_generate_messages_lisp
Built target mongodb_store_msgs_generate_messages_py
Built target mongodb_store_generate_messages_py
Built target move_base_msgs_generate_messages_lisp
[  0%] [  0%] Built target mongodb_store_msgs_generate_messages_cpp
Built target move_base_msgs_generate_messages_cpp
[  0%] [  0%] [  0%] Built target nav_msgs_generate_messages_py
Built target sensor_msgs_generate_messages_cpp
Built target nav_msgs_generate_messages_cpp
[  0%] Built target sensor_msgs_generate_messages_lisp
[  0%] Built target sensor_msgs_generate_messages_py
[  0%] [  0%] [  0%] Built target nav_msgs_generate_messages_lisp
Built target visualization_msgs_generate_messages_cpp
Built target visualization_msgs_generate_messages_py
[  0%] Built target tf_generate_messages_py
[  0%] [  0%] [  0%] [  0%] Built target tf_generate_messages_lisp
Built target tf2_msgs_generate_messages_cpp
[  0%] Built target tf2_msgs_generate_messages_lisp
Built target tf_generate_messages_cpp
Built target _occupancy_grid_utils_generate_messages_check_deps_LocalizedCloud
[  0%] [  0%] [  0%] Built target _occupancy_grid_utils_generate_messages_check_deps_NavigationFunction
Built target tf2_msgs_generate_messages_py
Built target _occupancy_grid_utils_generate_messages_check_deps_OverlayClouds
[  0%] Built target visualization_msgs_generate_messages_lisp
[  5%] [  9%] Built target rosplan_dispatch_msgs_generate_messages_cpp
[ 14%] Built target rosplan_dispatch_msgs_generate_messages_lisp
Built target rosplan_dispatch_msgs_generate_messages_py
[ 23%] Built target rosplan_knowledge_msgs_generate_messages_py
[ 30%] [ 32%] Built target occupancy_grid_utils_generate_messages_cpp
Built target rosplan_knowledge_msgs_generate_messages_cpp
[ 40%] Built target rosplan_knowledge_msgs_generate_messages_lisp
[ 42%] [ 43%] [ 43%] Built target occupancy_grid_utils_generate_messages_lisp
Built target occupancy_grid_utils_generate_messages_py
Built target rosplan_dispatch_msgs_generate_messages
[ 43%] Built target rosplan_knowledge_msgs_generate_messages
[ 44%] [ 44%] Building CXX object rosplan/rosplan_planning_system/CMakeFiles/print_plan.dir/src/print_plan.cpp.o
Built target occupancy_grid_utils_generate_messages
[ 44%] [ 47%] Built target rosplan_action_interface
Built target grid_utils
[ 48%] Built target simulatedAction
[ 48%] Built target grid_utils_boost_python_exports
[ 48%] Built target grid_construction_node
[ 65%] Built target planner
[ 66%] [ 83%] Built target rpsimplemapServer
Built target rosplan_planning_system
[ 84%] Built target rproadmapServer
[100%] Built target knowledgeBase
[100%] Built target rpmovebase
/home/srp/ROSPlan/src/rosplan/rosplan_planning_system/src/print_plan.cpp: In function ‘void plan_cb(const ConstPtr&)’:
/home/srp/ROSPlan/src/rosplan/rosplan_planning_system/src/print_plan.cpp:45:19: error: ISO C++ forbids declaration of ‘a’ with no type [-fpermissive]
  for (const auto &a : msg->plan) {
                   ^
/home/srp/ROSPlan/src/rosplan/rosplan_planning_system/src/print_plan.cpp:45:23: error: range-based ‘for’ loops are not allowed in C++98 mode
  for (const auto &a : msg->plan) {
                       ^
/home/srp/ROSPlan/src/rosplan/rosplan_planning_system/src/print_plan.cpp:47:20: error: ISO C++ forbids declaration of ‘p’ with no type [-fpermissive]
   for (const auto &p : a.parameters) {
                    ^
/home/srp/ROSPlan/src/rosplan/rosplan_planning_system/src/print_plan.cpp:47:24: error: range-based ‘for’ loops are not allowed in C++98 mode
   for (const auto &p : a.parameters) {
                        ^
/home/srp/ROSPlan/src/rosplan/rosplan_planning_system/src/print_plan.cpp:47:26: error: request for member ‘parameters’ in ‘a’, which is of non-class type ‘const int’
   for (const auto &p : a.parameters) {
                          ^
/home/srp/ROSPlan/src/rosplan/rosplan_planning_system/src/print_plan.cpp:48:17: error: request for member ‘value’ in ‘p’, which is of non-class type ‘const int’
    s += " " + p.value;
                 ^
/home/srp/ROSPlan/src/rosplan/rosplan_planning_system/src/print_plan.cpp:50:40: error: request for member ‘dispatch_time’ in ‘a’, which is of non-class type ‘const int’
   printf("%7.3f: (%s %s)  [%.3f]\n", a.dispatch_time, a.name.c_str(), s.c_str(), a.duration);
                                        ^
/home/srp/ROSPlan/src/rosplan/rosplan_planning_system/src/print_plan.cpp:50:57: error: request for member ‘name’ in ‘a’, which is of non-class type ‘const int’
   printf("%7.3f: (%s %s)  [%.3f]\n", a.dispatch_time, a.name.c_str(), s.c_str(), a.duration);
                                                         ^
/home/srp/ROSPlan/src/rosplan/rosplan_planning_system/src/print_plan.cpp:50:84: error: request for member ‘duration’ in ‘a’, which is of non-class type ‘const int’
   printf("%7.3f: (%s %s)  [%.3f]\n", a.dispatch_time, a.name.c_str(), s.c_str(), a.duration);
                                                                                    ^
make[2]: *** [rosplan/rosplan_planning_system/CMakeFiles/print_plan.dir/src/print_plan.cpp.o] Error 1
make[1]: *** [rosplan/rosplan_planning_system/CMakeFiles/print_plan.dir/all] Error 2
make: *** [all] Error 2
Invoking "make -j8 -l8" failed
`
I haven't understood really what is the problem 
Thank you

**Comment by m312z** [comment]
The first error comes from here:

> /home/srp/ROSPlan/src/rosplan/rosplan_planning_system/src/print_plan.cpp:45:19: error: ISO C++ forbids declaration of ‘a’ with no type [-fpermissive]

I've updated the loop in print_plan to use a simple FOR loop which should be supported. It should now compile.

Michael

**Comment by ismaisma** [comment]
Hi, 
problem solved 
it works perfectly
Thank you  
Isma
