### ISSUE TITLE
No Log File Generation for Failed Plan

### ISSUE THREAD

**Issue by Archetype90** [KCL-Planning/ROSPlan#70]
I have a PDDL domain, which I found in the following repo:

https://bitbucket.org/planning-researchers/classical-domains/src/208a850d2ff2a27068329ad578ad99af9ec7e5c5/classical/tsp/domain.pddl?at=master&fileviewer=file-view-default

My goal was to find as simple of a PDDL example as possible and build a custom component around that PDDL. 

The PDDL domain is as follows: 

```
(define (domain tsp)

(:requirements :strips :typing :fluents :disjunctive-preconditions :durative-actions)

  (:types 
  	location)

  (:predicates
     (at ?x - location)
     (visited ?y - location))

  (:action move
	:parameters (?x ?y)
	:precondition (at ?x)
	:effect (and (at ?y) (visited ?y) (not (at ?x))))
)
```

After launching the Planning System and all other components (using a modified interfaced_planning_system.launch that replaces the domain and component) everything seems to be fine. I then rush a bash script to populate my knowledge base and start the planning system. 

After running the bash script, I see the following log messages: 

```
[ INFO] [1515784983.314983688]: KCL: (KB) Adding instance (location, 1)
[ INFO] [1515784983.876731650]: KCL: (KB) Adding instance (location, 2)
[ INFO] [1515784985.185522507]: KCL: (KB) Adding domain attribute (at location=1)
[ INFO] [1515784985.883142831]: KCL: (KB) Adding mission goal ( visited=1)
[ INFO] [1515784986.524591316]: KCL: (PS) Parsing domain: /home/ros/ros_plan/src/rosplan/rosplan_demos/common/domain_tdl.pddl.
[ INFO] [1515784986.524948030]: KCL: (PS) File does exist: /home/ros/ros_plan/src/rosplan/rosplan_demos/common/domain_tdl.pddl.
[rosplan_planning_system-4] process has died [pid 65091, exit code -11, cmd /home/ros/ros_plan/devel/lib/rosplan_planning_system/planner __name:=rosplan_planning_system __log:=/home/ros/.ros/log/7d2364d4-f6ff-11e7-aaf0-000c2948cd07/rosplan_planning_system-4.log].
log file: /home/ros/.ros/log/7d2364d4-f6ff-11e7-aaf0-000c2948cd07/rosplan_planning_system-4*.log
```

The log file that it specifies (rosplan_planning_system-4*.log) does not exist at all. In fact, that folder does not contain any rosplan_planning_system logs at all. 

What I would like to understand, is why it crashes and does not produce a log message with what I believe is valid PDDL?

**Comment by m312z** [comment]
Hello there,

It looks like the output you show here says: "File does exist". This would mean that in both cases the file is found.

I think that the crash is due to missing types in the action parameters:
> :parameters (?x ?y)

Try:
> :parameters (?x ?y - location)

If that works, then it looks like there is a bug in the domain parser -- not checking for the existence of types before trying to read them. Hopefully you are able to use typed parameters and avoid this issue for now.

Michael

**Comment by m312z** [comment]
@b-dorian

**Comment by Archetype90** [comment]
Thanks a lot for the reply @m312z. What a silly mistake on my behalf. Your solution did work and removed the error. I have updated the question to more accurately reflect the useful information that you have provided, and not my mistake.

Thank you again for your reply!
