### ISSUE TITLE
Current version of ROSPlan doesn’t specify usage of ontology in detail?

### ISSUE THREAD

**Issue by yashu88** [KCL-Planning/ROSPlan#79]
I have check ROSPlan GitHub source code in details as well I have read your research article. In ROSPlan framework inside rosplan_planning_system/src/PlanningSystem.cpp file you have mentioned about update the environment from the ontology. Further I didn’t find any details regarding how you utilize ontology in given ROSPlan framework. Because in research article you have mentioned waypoints are created using a probabilistic road map (PRM) and stored in the ontology. But in given framework mapping interface generate waypoints (waypoint generation depend on scripts/turtlebot_explore.bash) and stored symbolically in the Knowledge Base. Kindly clarify how you utilize ontology to form a semantic map of the environment?
![screenshot from 2018-02-26 17-01-26](https://user-images.githubusercontent.com/13538238/36663511-2597438a-1b25-11e8-8a6b-5153cc6afdda.png)

**Comment by oscar-lima** [comment]
This is a repeated issue, please check: #80
