### ISSUE TITLE
Cannot find rosplan_config: documentation issue (and fix)

### ISSUE THREAD

**Issue by cmahieu-intec** [KCL-Planning/ROSPlan#95]
The documentation [here](http://kcl-planning.github.io/ROSPlan/documentation/planning_system_launch.html) should be updated to change the mentions of "rosplan_config" to "rosplan_planning_system".

Old launch file code:

`
<param name="domain_path" value="$(find rosplan_demos)/common/domain_turtlebot.pddl" />

<node name="rosplan_planning_system" pkg="rosplan_planning_system" type="planner" respawn="false" output="screen">
	
	<param name="data_path" value="$(find rosplan_config)/planner/" />
	<param name="problem_path" value="$(find rosplan_config)/planner/problem.pddl" />
	<param name="strl_file_path" value="$(find rosplan_config)/planner/plan.strl" />

	
	<param name="planner_command" value="timeout 10 $(find rosplan_config)/planner/bin/popf -n DOMAIN PROBLEM" />
	<param name="generate_default_problem" value="true" />
	<param name="max_dispatch_attempts" value="2" />
</node>`

New launch file code:

`
	<param name="domain_path" value="$(find rosplan_demos)/common/domain_turtlebot.pddl" />

	
	<node name="rosplan_planning_system" pkg="rosplan_planning_system" type="planner" respawn="false" output="screen">
		
		<param name="data_path" value="$(find rosplan_planning_system)/planner/" />
		<param name="problem_path" value="$(find rosplan_planning_system)/planner/problem.pddl" />
		<param name="strl_file_path" value="$(find rosplan_planning_system)/planner/plan.strl" />

		
		<param name="planner_command" value="timeout 10 $(find rosplan_planning_system)/planner/bin/popf -n DOMAIN PROBLEM" />
		<param name="generate_default_problem" value="true" />
		<param name="max_dispatch_attempts" value="2" />
	</node>`

**Comment by m312z** [comment]
Finally updated the documentation; the new file is here:
http://kcl-planning.github.io/ROSPlan//documentation/interfaces/02_planner_interface.html
along with tutorials.
